### ISSUE TITLE
General question regarding API usage/behaviour

### ISSUE THREAD

**Issue by chillerno1** [yifeikong/aioify#19]
Recently came across aioify and it's been great to use so far. In saying that, I do have one question about a the API that I was hoping someone could answer.

For context, I wanted to see if I could use `aioify` on `CoinGeckoAPI()` (from the pycoingecko library, wrapper for crypto web API) and then call its methods in an async fashion. The issue I'm seeing is; some methods don't return a coroutine when they should.

Methods:
- `cg.get_coin_by_id(id="bitcoin")`
- `cg.get_supported_vs_currencies()`

**Issue** (see comments for context):
```python
import asyncio
from aioify import aioify
from pycoingecko import CoinGeckoAPI

cg = aioify(obj=CoinGeckoAPI(), name='cg')

async def main():

    # using await
    await cg.get_coin_by_id(id="bitcoin") # throws ‘TypeError: object dict can't be used in 'await' expression’
    await cg.get_supported_vs_currencies() # returns expected result

    # without await
    cg.get_coin_by_id(id="bitcoin") # returns expected result
    cg.get_supported_vs_currencies() # throws 'RuntimeWarning: coroutine 'CoinGeckoAPI.get_supported_vs_currencies' was never awaited'
    
    # what works
    cg.get_coin_by_id(id="bitcoin") # returns expected result
    await cg.get_supported_vs_currencies() # returns expected result

if __name__ == '__main__':
    asyncio.run(main())
```

Both methods simply query an endpoint and return the result. After comparing the two, the one difference is an internal wrapper `@list_args_to_comma_separated` on `get_coin_by_id` (this wraps many other methods in the library also).

```python
# source: https://github.com/man-c/pycoingecko/blob/8b7a8451cc8911eff5a7f268c885da4bc1570c3f/pycoingecko/api.py

   def get_supported_vs_currencies(self, **kwargs):
        """Get list of supported_vs_currencies"""
   ...

   @list_args_to_comma_separated
   def get_coin_by_id(self, id, **kwargs):
       """Get current data (name, price, market, ... including exchange tickers) for a coin"""
    ...
```

Taking a stab in the dark, I suspect this issue occurs because `@list_args_to_comma_separated` is external to the CoinGeckoAPI object and it doesn't get "aioify-ed". When `get_coin_by_id` is executed, `@list_args_to_comma_separated` probably breaks aioify's async and returns the result as if it was a regular function rather than a coroutine.

Is there any way to handle this scenario? The expectation being both methods should be awaited.

**Comment by rominf** [comment]
@chillerno1 Hi. I've made a fix (you can grab the latest version from PyPI). I hope it helps.

**Comment by chillerno1** [comment]
@rominf New version works perfect. Tyvm for your help!
