### ISSUE TITLE
[QUESTION] Using asyncio.gather() with @aioify functions

### ISSUE THREAD

**Issue by atDTSystemsLtd** [yifeikong/aioify#20]
I wonder how much of a shortcut Aioify really provides (on a way to async python).

One of the ways I would like to use Aiofy is to issue number of REST requests concurrently. Code looks something like this:

```python
async def call_many_rest_async():
   result = await asyncio.gather(
        call_rest1_async(),
        call_rest2_async(),
        ...
   )
   # do something with result 

...
@aioify
def call_rest1_async():
   return call_rest1()
@aioify
def call_rest2_async():
   return call_rest2()
```

The question is, will the code above execute the REST calls sequentially or concurrently? I am afraid that the answer is - sequentially. Am I wrong?

**Comment by atDTSystemsLtd** [comment]
Interesting... it seems that I am wrong.

**Comment by rominf** [comment]
@atDTSystemsLtd I assume I can close the issue. Please comment otherwise.
