### ISSUE TITLE
How to join current thread by calling aioify?

### ISSUE THREAD

**Issue by xho22** [yifeikong/aioify#21]
I found my threadlocal value doesn't work in aioify since it create a new thread named 'ThreadPoolExecutor-2_0:140634794800200' to handle coroutine code.
```
del my_func():
    pass

async_call = aioify(obj=my_func, name='run_async_my_func')

await async_call()
```
```
2021-07-09-16:12:32  xxxxxxxxxxxxxxx "2021-07-09 16:12:32,464 [INFO] <ThreadPoolExecutor-2_0:140634794800200>
```
How to avoid creating new thread and just join to current thread?
Here is my workaround by using native asyncio now:
```
del my_func():
    pass

def async_call():
    import asyncio
    return asyncio.coroutine(my_func)()

await async_call()
```

**Comment by rominf** [comment]
Hi. Sorry for the very long delay. I've put the library into maintenance mode (see reasons and proper ways to do similar things in README.md).
